// COMPANY_CONFIG — The supplier/company's own fixed address.
// Shown in the "FROM (Supplier / Our Company)" section of the Purchase Order.
// Only editable by Manager in Super Admin settings (not implemented yet — hardcoded).
export const COMPANY_CONFIG = {
  name: "Jai Sakthi Packaging",
  address: "58, Annai Avenue, Rathnamangalam, Near Tagore Medical College",
  city: "Chennai",
  state: "Tamil Nadu",
  stateCode: "33",
  pincode: "600000",
  gstin: "",
  pan: "",
  cin: "",
  phone: "9884200477",
  email: "",
};

// SELLER_CONFIG — Hardcoded company seller defaults for Tax Invoice.
// Shown as the company identity on Tax Invoices generated by Dispatch.
// Only editable by Manager in Super Admin settings (not implemented yet — hardcoded).
export const SELLER_CONFIG = {
  name: "Jai Ganesh Polypack",
  address:
    "Survey No 2/5, Door No 2/353A, V.K Industrial Estate, Earikkarai, Parivakkam Main Road, Senneerkuppam, Chennai 600056",
  gstin: "33AAUJF5682M1ZJ",
  state: "Tamil Nadu",
  stateCode: "33",
  email: "jaiganeshpolypack@gmail.com",
};
